//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookChef.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        public People()
        {
            this.Transactions = new HashSet<Transactions>();
        }
    
        public long Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Birthday { get; set; }
        public string ControlNumber { get; set; }
    
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
