//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookChef.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Books = new HashSet<Books>();
        }
    
        public long Id { get; set; }
        public string Label { get; set; }
    
        public virtual ICollection<Books> Books { get; set; }
    }
}
