//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookChef.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public long Id { get; set; }
        public double Date { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Pnum { get; set; }
        public string BookTitle { get; set; }
        public string BookIsbn { get; set; }
        public string BookAuthor { get; set; }
        public string BookPublisher { get; set; }
        public string TransactionLabel { get; set; }
    }
}
