//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookChef.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public long Id { get; set; }
        public double Date { get; set; }
        public long PersonId { get; set; }
        public long BookId { get; set; }
        public string Description { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual People People { get; set; }
    }
}
